[package]
name = "uci"
version = "0.1.0"
authors = ["CrazyMerlyn <crazy.d.merlyn@gmail.com>"]
description = "A library to programmatically communicate with UCI compatible chess engines"

[dependencies]
log = "0.3.6"

